name: CI Checks
on: [pull_request, push]

jobs:
    checks:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v6

          - name: Set up Java
            uses: actions/setup-java@v4
            with:
              distribution: temurin
              java-version: 21

          - name: Set up Gradle
            uses: gradle/actions/setup-gradle@v6

          - name: Build with Gradle
            run: ./gradlew build

          - name: Run Unit Tests (Controllers)
            run: ./gradlew test --tests "*ControllerTest"

          - name: Run Unit Tests (Services)
            run: ./gradlew test --tests "*ServiceTest"

          - name: Run Unit Tests (Repositories)
            run: ./gradlew test --tests "*RepositoryImplTest"

          - name: Run Integration Tests
            run: ./gradlew test --tests "*IntegrationTest"

          - name: Run Linter
            run: ./gradlew ktlintCheck